[package]
name = "hfst-pmatch"
version = "0.1.0"
edition = "2021"
description = "perform matching/lookup on text streams"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
